name: Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            platform: linux-x64
            packageName: default
            resultFile: './result/lib/libgit2.so'
          - runs-on: ubuntu-24.04-arm
            platform: linux-arm64
            packageName: default
            resultFile: './result/lib/libgit2.so'
          - runs-on: macos-latest
            platform: darwin-arm64
            packageName: default
            resultFile: './result/lib/libgit2.dylib'
          - runs-on: macos-latest
            platform: darwin-x64
            packageName: x64Darwin
            resultFile: './result/lib/libgit2.dylib'
          - runs-on: ubuntu-latest
            platform: win32-x64
            packageName: windows
            resultFile: './result/bin/libgit2.dll'

    runs-on: ${{ matrix.runs-on }}

    outputs:
      artifacts: ${{ steps.collect-artifacts.outputs.artifacts }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
        env:
          NIX_FIRST_BUILD_UID: "351"

      - name: Build project
        run: nix build .#${{ matrix.packageName }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libgit2-${{ matrix.platform }}
          path: ${{ matrix.resultFile }}
          retention-days: 1
